development:

  secret_key_base: xxxxxxxxxxxxxxxxxxxx
  stripe_publishable_key: pk_test_WauyB2DNzaFtf6Hsl0Hk1eaz
  stripe_secret_key: sk_test_hGROFnJhqoh2DrMFTdoKQCUP

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
